import type { Metadata } from 'next';
import { Noto_Sans, Tomorrow } from 'next/font/google';
import './globals.css';
import { Footer, Topbar } from '@/components';
import Faq from './_faq';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

const tomorrow = Tomorrow({
  variable: '--font-tomorrow',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'GrandTrip Sulawesi',
  description: 'Generated by create next app',
  icons: {
    icon: [
      { url: '/favicon-16x16.png', sizes: '16x16', type: 'image/png' },
      { url: '/favicon-32x32.png', sizes: '32x32', type: 'image/png' },
    ],
    apple: [
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${tomorrow.variable} antialiased relative`}
      >
        <Topbar />
        {children}
        <Faq />
        <Footer />
      </body>
    </html>
  );
}
