import type { Metadata } from 'next';
import { Noto_Sans, Tomorrow } from 'next/font/google';
import './globals.css';
import { Footer, Topbar } from '@/components';

const notoSans = Noto_Sans({
  variable: '--font-noto-sans',
  subsets: ['latin'],
});

const tomorrow = Tomorrow({
  variable: '--font-tomorrow',
  subsets: ['latin'],
  weight: ['400', '600', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${notoSans.variable} ${tomorrow.variable} antialiased relative`}
      >
        <Topbar />
        {children}
        {/* <Footer /> */}
      </body>
    </html>
  );
}
